import Feature from "@/components/Homepage/Feature";
import Hero from "@/components/Homepage/Hero";
import Services from "@/components/Homepage/Services";
import WorkInfo from "@/components/Homepage/WorkInfo";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Sodia Agency</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <Feature />
      <Services />
      <WorkInfo />
    </>
  );
}
