import BranchMarquee from "@/components/Homepage/BranchMarquee";
import Feature from "@/components/Homepage/Feature";
import Hero from "@/components/Homepage/Hero";
import Pricing from "@/components/Homepage/Pricing";
import Services from "@/components/Homepage/Services";
import Testimonial from "@/components/Homepage/Testimonial";
import WorkInfo from "@/components/Homepage/WorkInfo";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Sodia Agency</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700;800;900&family=Rubik:wght@400;500;700&display=swap"
          rel="stylesheet"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <Feature />
      <Services />
      <WorkInfo />
      <Pricing />
      <Testimonial />
      <BranchMarquee />
    </>
  );
}
